name: 'Build pkgdown site'
description: 'Builds a pkgdown site from the source files of the package at package_root'
inputs:
  package_root:
    description: 'The root directory of the source tree of an R package'
    default: ${{ github.workspace }}
runs:
  using: "composite"
  steps:

    - name: Test for Pandoc
      id: pandoc-test
      run: pandoc --version
      shell: bash
      continue-on-error: true

    - name: Install Pandoc
      if: always() && steps.pandoc-test.outcome == 'failure'
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install TinyTex
      run: |
        install.packages('tinytex')
        tinytex::install_tinytex()

        # (tinytex::pdflatex, which is called by the
        # pdf_vignette_index.Rmd vignette, will automatically install
        # any additional needed LaTeX packages needed by the Rnw
        # vignettes.)

      shell: Rscript {0}

    - name: Run pkgdown
      run: |
        cd ${{ inputs.package_root }}/documentation/script
        ./run_pkgdown.sh
      shell: bash
