name: 'Render Bookdown Book'
description: ''
inputs:
  repository-root:
    description: 'The root of the repository containing the bookdown source files'
    required: true
runs:
  using: "composite"
  steps:
    - name: Test for Pandoc
      run: pandoc --version
      shell: bash
      continue-on-error: true

    - name: Install Pandoc
      if: failure()
      uses: r-lib/actions/setup-pandoc@v1

    - name: 8. Install bookdown
      run: |
        install.packages(c("bookdown"))
      shell: Rscript {0}

    - name: 9. Run bookdown
      run: |
        cd ${{ inputs.repository-root }}/documentation/script
        ./run_bookdown.sh
      shell: bash
