name: Generate documentation

on:
  push:
    branches:
      - main

    tags:
      - '*'

  # This event creates an artifact for download but does not write to
  # the BioCro documentation repository:
  pull_request:

  workflow_dispatch:
    inputs:
      pkgdown-build:
        description: Build the pkgdown site
        type: boolean
        default: true
      bookdown-build:
        description: Build the developer manual
        type: boolean
        default: true
      doxygen-build:
        description: Build the Doxygen documentation
        type: boolean
        default: true

env:
  # The documentation repository:
  PUBLISH_TO: "gsrohde/eraseme"
  # Relative path from the GitHub workspace directory to the directory
  # where the documentation repository will be checked out:
  BIOCRO_DOCUMENTATION_ROOT: biocro_documentation_repository
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    name: Build pkgdown, bookdown, and Doxygen documentation

    runs-on: ubuntu-latest

    steps:

    - name: 1. Check out repository
      uses: actions/checkout@v2

    - name: 2. Set up R
      if: inputs.bookdown-build || inputs.pkgdown-build
      uses: r-lib/actions/setup-r@v2

    - name: 3a. Install dependencies and pkgdown
      if: inputs.pkgdown-build
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::pkgdown, local::.

    - name: 3b. Install dependencies
      if: inputs.bookdown-build && !inputs.pkgdown-build
      uses: r-lib/actions/setup-r-dependencies@v2

    - name: 4. Build Bookdown book
      if: inputs.bookdown-build
      uses: './.github/actions/render_bookdown_book'

    - name: 5. Build pkgdown book
      if: inputs.pkgdown-build
      uses: ./.github/actions/build_pkgdown_site

    - name: 6. Build Doxygen documentation
      if: inputs.doxygen-build
      uses: ./.github/actions/run_doxygen

    # The "PUBLISH_TO" repository is where the documentation will be
    # pushed to (on the default branch).  Providing ssh-key to this
    # checkout action gives us permission to check in our changes
    # later, in the Push step:

    - name: 7. Check out the target "PUBLISH_TO" repository
      if: github.event_name != 'pull_request'
      uses: actions/checkout@v2
      with:
        repository: ${{ env.PUBLISH_TO }}
        path: ${{ env.BIOCRO_DOCUMENTATION_ROOT }}
        ssh-key:  ${{ secrets.PRIVATE_SSH_KEY }}

    - name: 8. "Copy newly-generated documentation files into working
                copy of the target repository"

      if: github.event_name != 'pull_request'

      env:

        # The Doxygen version directory names are hard-coded into the
        # Make file and are determined by the Make target.  An
        # exception to this is
        # "doxygen_docs_modules_public_members_only", which is
        # explicitly set as an output directory in the run_doxygen
        # action, overriding the default output directory for the Make
        # file target "module-docs-html".  (The default output
        # directory "doxygen_docs_modules" was already used as the
        # output directory for a version of the module documentation
        # that included documentation of private members, and we don't
        # want to overwrite it.)

        version_directories: "doxygen_docs_complete doxygen_docs_modules doxygen_docs_modules_public_members_only doxygen_docs_framework"

      working-directory: ${{ env.BIOCRO_DOCUMENTATION_ROOT }}

      run: |
        # (Re)create target documentation directory:
        mkdir -p $VERSION

        # Copy the respective documentation into them:

        if [[ ${{ inputs.pkgdown-build }} == true ]]
        then
            echo "Copying pkgdown files"
            rsync -a --delete --filter "protect /bookdown_book" \
                              --filter "protect /doxygen" \
                  -v -v ../docs/ $VERSION || true
        fi

        if [[ ${{ inputs.bookdown-build }} == true ]]
        then
            echo "copying bookdown files"
            rsync -a --delete ../bookdown/_book/ $VERSION/bookdown_book || true
        fi

        if [[ ${{ inputs.doxygen-build }} == true ]]
        then
            echo "copying doxygen files"
            mkdir -p $VERSION/doxygen
            for dir in ${{ env.version_directories }}; do

                # Copy the documentation for version $dir:
                rsync -a --delete ../doxygen/$dir/html/ $VERSION/doxygen/$dir || true

            done
        fi

    - name: 9. Commit updates and push to target (documentation) repository

      if: github.event_name != 'pull_request'

      working-directory: ${{ env.BIOCRO_DOCUMENTATION_ROOT }}
      run: |

        # user.name is somewhat arbitrary but must be provided:
        git config user.name biocro-action
        git add .
        git commit -m "generated pgkdown and bookdown documentation"
        git push

    - name: 10. Zip documentation
      if: always() # Even if some steps fail, at least try to make a documentation artifact.
      run: |
        tar -czf biocro-docs-from-$VERSION.tgz -C $BIOCRO_DOCUMENTATION_ROOT/$VERSION .

    - name: 11. Upload artifact containing documentation
      if: always() # Even if some steps fail, at least try to make a documentation artifact.
      uses: actions/upload-artifact@v2
      with:
        name: biocro-documentation
        path: biocro-docs-from-${{ env.VERSION }}.tgz
