on:
  workflow_call:
    inputs:
      os:
        type: string
      r-version:
        type: string
      check-manual:
        type: string
      run-tests:
        type: string
      check-examples:
        type: string
      check-vignettes:
        type: string
      needs-tinytex:
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "os ${{ inputs.os }}"
          echo "r-version ${{ inputs.r-version }}"
          echo "check-manual ${{ inputs.check-manual }}"
          echo "run-tests ${{ inputs.run-tests }}"
          echo "check-examples ${{ inputs.check-examples }}"
          echo "needs-tinytex ${{ inputs.needs-tinytex }}"
