on:
  workflow_call:
    inputs:
      strategy-matrix:
        type: string
      check-manual:
        type: string
      run-tests:
        type: string
      check-examples:
        type: string
      check-vignettes:
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo strategy-matrix ${{ inputs.strategy-matrix }}
          echo check-manual ${{ inputs.check-manual }}
          echo run-tests ${{ inputs.run-tests }}
          echo check-examples ${{ inputs.check-examples }}
          echo check-vignettes ${{ inputs.check-vignettes }}

  use-strategy-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.strategy-matrix) }}
    steps:
      - run: |
          echo os ${{ matrix.os }}
          echo R version ${{ matrix.r }}
