name: run-R-CMD-check

on:
  workflow_dispatch:
    # When running manually, allow users to customize the run:
    inputs:
      # What options should be passed to "R CMD check"?
      check-manual:
        description: 'Check the manual'
        type: boolean
        default: true
      check-vignettes:
        description: 'Check the vignettes'
        type: boolean
        default: true
      run-tests:
        description: 'Run the tests (yes/no)'
        type: boolean
        default: true
      check-examples:
        description: 'Check the examples (yes/no)'
        type: boolean
        default: true

      # Which platform should we test?
      platform-to-check:
        description: 'Platform to check'
        type: choice
        options:
          - R 3.5 on macOS
          - R 3.5 on Windows
          - R 3.5 on Ubuntu
          - R release version on Ubuntu
          - R devel version on Ubuntu
        default: R 3.5 on Ubuntu

jobs:

  matrix_prep:
    name: Prepare strategy matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        name: Conditional Build Matrix
        uses: JoshuaTheMiller/conditional-build-matrix@0.0.1
        with:
          inputFile: '.github/workflows/strategy_matrix.json'

          # This filter uses the JMESPath query language to modify the
          # strategy matrix.  See https://jmespath.org/.
          filter:
            '[?configName == `${{ github.event.inputs.platform-to-check }}`]'

  # For debugging:
  display_matrix:
    name: Display strategy matrix
    needs: matrix_prep # Supplies matrix output.
    runs-on: ubuntu-latest
    steps:
    - name: Report Configuration
      env:
        MATRIX_CONTEXT: ${{ needs.matrix_prep.outputs.matrix }}
      run: |
        echo "matrix: $MATRIX_CONTEXT"

  call-R-CMD-check:
    #uses: ./.github/workflows/new-R-CMD-check.yaml
    needs: matrix_prep
    uses: ./.github/workflows/print-inputs.yaml
    with:
      strategy-matrix: ${{ needs.matrix_prep.outputs.matrix }}
      check-manual: ${{ github.event.inputs.check-manual }}
      run-tests: ${{ github.event.inputs.run-tests }}
      check-examples: ${{ github.event.inputs.check-examples }}
      check-vignettes: ${{ github.event.inputs.check-vignettes }}

