# This workflow can only be run manually for now, as it uses macOS as
# a runner, which is expensive.

name: Generate pkgdown and bookdown documentation

on:
  push:
    branches:
      - main

    tags:
      - '*'

  pull_request:

  workflow_dispatch:
    inputs:
      pkgdown-build:
        description: Build the pkgdown site
        type: boolean
        default: true
      bookdown-build:
        description: Build the developer manual
        type: boolean
        default: true
      doxygen-build:
        description: Build the Doxygen documentation
        type: boolean
        default: true

env:
  PUBLISH_TO: "gsrohde/biocro-documentation"
  VERSION: ${{ github.ref_name }}
  BIOCRO_DOCUMENTATION_ROOT: biocro_documentation_repository

jobs:
  build:
    name: Generate pkgdown and bookdown documentation

    runs-on: ubuntu-latest

    steps:

    - name: 1. Check out repository
      uses: actions/checkout@v2

    - name: (debug) Generate file list
      if: ${{ always() }}
      continue-on-error: true
      run: |
        pwd
        echo ${{ github.workspace }}
        echo $GITHUB_WORKSPACE
        ls -la
        ls -la ${{ github.workspace }}
        la -la $GITHUB_WORKSPACE
        find . > file_list

    - name: (debug) Upload artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: File_list
        path: file_list

    - name: 2. Set up R
      if: failure() || inputs.bookdown-build || inputs.pkgdown-build
      uses: r-lib/actions/setup-r@v2

    - name: 3a. Install dependencies and pkgdown
      if: inputs.pkgdown-build
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::pkgdown, local::.

    - name: 3b. Install dependencies
      if: inputs.bookdown-build && !inputs.pkgdown-build
      uses: r-lib/actions/setup-r-dependencies@v2

    - name: 4. Build Bookdown book
      if: inputs.bookdown-build
      uses: './.github/actions/render_bookdown_book'

    - name: 5. Build pkgdown book
      if: inputs.pkgdown-build
      uses: ./.github/actions/build_pkgdown_site

    - name: 6. Build Doxygen documentation
      if: inputs.doxygen-build
      uses: ./.github/actions/run_doxygen

    # The "PUBLISH_TO" repository is where the documentation will be
    # copied to and then checked in (to the default branch).
    # Providing ssh-key to this checkout action gives us permission to
    # check in our changes later, in the Push step:

    - name: 7. Check out master of the "PUBLISH_TO" repository
      uses: actions/checkout@v2
      with:
        repository: ${{ env.PUBLISH_TO }}
        path: ${{ env.BIOCRO_DOCUMENTATION_ROOT }}
        ssh-key:  ${{ secrets.PRIVATE_SSH_KEY }}

    - name: 8. Copy files into working copy of the target repository

      env:

        # The version directory names are hard-coded into the Make
        # file and are determined by the Make target.  An exception to
        # this is "doxygen_docs_modules_public_members_only", which is
        # explicitly set as an output directory in the
        # build_pkgdown_site action, overriding the default output
        # directory for the Make file target "module-docs-html".  (The
        # default output directory "doxygen_docs_modules" was already
        # used as the output directory for a version of the module
        # documentation that included documentation of private
        # members, and we don't want to overwrite it.)

        version_directories: "doxygen_docs_complete doxygen_docs_modules doxygen_docs_modules_public_members_only doxygen_docs_framework"

      working-directory: ${{ env.BIOCRO_DOCUMENTATION_ROOT }}

      run: |
        # (Re)create target documentation directory:
        mkdir -p $VERSION

        # Copy the respective documentation into them:
        rsync -a --delete --filter "protect /$VERSION/bookdown_book" \
                          --filter "protect /$VERSION/doxygen" \
              ../docs/ $VERSION || true
        rsync -a --delete ../bookdown/_book/ $VERSION/bookdown_book || true

        mkdir -p $VERSION/doxygen
        for dir in ${{ env.version_directories }}; do

            # Copy the documentation for version $dir:
            rsync -a --delete ../doxygen/$dir/html/ $VERSION/doxygen/$dir || true

        done

    - name: 9. Commit updates and push to target (documentation) repository

      working-directory: ${{ env.BIOCRO_DOCUMENTATION_ROOT }}
      run: |

        # user.name is somewhat arbitrary but must be provided:
        git config user.name biocro-action
        git add .
        git commit -m "generated pgkdown and bookdown documentation"
        git push

    - name: (Tentative) Upload artifact containing documentation
      uses: actions/upload-artifact@v2
      with:
        name: pkgdown-documentation
        path: ${{ env.BIOCRO_DOCUMENTATION_ROOT }}/${{ env.VERSION }}
